# Generated by Django 4.2.10 on 2024-03-10 16:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_file_file1_alter_file_file2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to=api.models.file_upload_path),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="file",
            name="file1",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file2",
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="file",
            name="excel_files",
            field=models.ManyToManyField(related_name="files", to="api.excelfile"),
        ),
    ]
