# Generated by Django 4.2.10 on 2024-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_excelfile_remove_file_file1_remove_file_file2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelfile",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
