# Generated by Django 4.2.10 on 2024-03-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_file_title_remove_file_excel_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="file",
            name="excel_files",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="api.excelfile",
            ),
        ),
    ]
