# Generated by Django 4.2.10 on 2024-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_file_title_alter_file_excel_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(blank=True, upload_to="excel"),
        ),
        migrations.RemoveField(
            model_name="file",
            name="excel_files",
        ),
        migrations.AddField(
            model_name="file",
            name="excel_files",
            field=models.ManyToManyField(related_name="files", to="api.excelfile"),
        ),
    ]
