# Generated by Django 4.2.10 on 2024-03-11 05:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_project_remove_file_excel_files_file_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="header",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, upload_to=api.models.file_upload_path),
        ),
    ]
