# Generated by Django 4.2.10 on 2024-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapping",
            name="primary_key",
            field=models.JSONField(),
        ),
    ]
