# Generated by Django 4.2.10 on 2024-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_mapping_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapping",
            name="dest",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
