# Generated by Django 4.2.10 on 2024-03-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_mapping_sql_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AlterField(
            model_name="mapping",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AlterField(
            model_name="sql",
            name="mapping",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.mapping"
            ),
        ),
    ]
