# Generated by Django 4.2.10 on 2024-03-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_terminal_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="Project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.project",
            ),
        ),
    ]
